import Head from 'next/head'
import Topnav from '../components/navbar/Topnav'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Footer from '../components/navbar/Footer'
import CustomerLikes from '../components/likedcollection/CustomerLikes'
import Product from '../components/Products/Product'
import DeliveryOption from '../components/customers/DeliveryOption'
import { ProductDetails } from '../components/customers/ProductDetails'
import Rating from '../components/customers/Rating'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Myntra responsive UI</title>
        <meta name="description" content="Generated by create next app" />
        <script src="https://kit.fontawesome.com/79dfc2e9eb.js" crossorigin="anonymous"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Topnav />
        <div>
          <Link href='/' >
            <a>Home</a>
          </Link>/
          <Link href='/' >
            <a>Clothing</a>
          </Link>/
          <Link href='/' >
            <a>Men Cloting</a>
          </Link>/
          <Link href='/' >
            <a>TShirts</a>
          </Link>
        </div>
        <Product />
        <DeliveryOption />
        <ProductDetails />
        <Rating />
        <CustomerLikes />

      </main>
      <footer className={styles.footer}>
        <Footer />
      </footer>
    </div>
  )
}
